targets:
  $default:
    builders:
      json_serializable:
        options:
          explicit_to_json: true 
          field_rename: snake
global_options:
  freezed:freezed:
    runs_before:
      - objectbox_generator:objectbox_generator