blank_issues_enabled: false
contact_links:
  - name: 📋 Mensa Online board
    url: https://github.com/orgs/Mensa-Italia/projects/2
    about: Vedi lo stato di sviluppo della piattaforma (tutti i repo).
