

on: push


jobs:

  ####################################################################################################

  #  BUILD IOS

  ####################################################################################################

  Android_App_IOS:
    name: Android App IOS
    runs-on: macos-latest
    steps:
      - name: Prepering Project
        uses: actions/checkout@v1

      - name: Prepering Java
        uses: actions/setup-java@v1
        with:
          java-version: '12.x'

      - name: Prepering Flutter
        uses: subosito/flutter-action@v1.3.1

      - name: Building App IOS
        env:
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          ALIAS_PASSWORD: ${{ secrets.ALIAS_PASSWORD }}
        run: flutter pub get && flutter build ios --no-codesign --release


      - name: Make Artifact
        uses: actions/upload-artifact@v1
        with:
          name: release-app-ios
          path: build/app/outputs/ios/release/app-release.ipa

      - name: Make Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/ios/release/app-release.ipa"
          allowUpdates: true
          artifactContentType: "aab"
          name: "release"
          tag: "release"
          token: ${{ secrets.GITHUB_TOKEN }}

