


on: push


jobs:

  IOS_App_:
    name: IOS App
    runs-on: macos-latest
    steps:
      - name: Prepering Project
        uses: actions/checkout@v1

      - name: Prepering Java
        uses: actions/setup-java@v1
        with:
          java-version: '12.x'

      - name: Prepering Flutter
        uses: subosito/flutter-action@v1.3.1

      - name: Adding signing key for Play Store
        env:
          KEY_JKS: ${{ secrets.KEY_JKS }}
        run: echo "$KEY_JKS" | base64 --decode > "/home/runner/work/mensa_italia_app/mensa_italia_app/android/key.jks"

      - name: Building App IOS
        env:
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          ALIAS_PASSWORD: ${{ secrets.ALIAS_PASSWORD }}
        run: flutter pub get && flutter build ios --release

      - name: Make Artifact
        uses: actions/upload-artifact@v1
        with:
          name: release-app-ios
          path: build/app/outputs/ios/release/app-release.ipa

      - uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/ios/release/app-release.ipa"
          allowUpdates: true
          artifactContentType: "ipa"
          name: "release-android-ios"
          tag: "release-android-ios"
          token: ${{ secrets.GITHUB_TOKEN }}

