on: push
jobs:
  Android_App_Bundle:
    name: Android App Bundle
    runs-on: ubuntu-latest
    steps:
      - name: Prepearing Checkout
        uses: actions/checkout@v1
      - name: Prepearing Java
        uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - name: Prepearing Flutter
        uses: subosito/flutter-action@v1.3.1
      - name: Adding signing key for Play Store
        env:
          KEY_JKS: ${{ secrets.KEY_JKS }}
        run: echo "$KEY_JKS" | base64 --decode > "/home/runner/work/mensa_italia_app/mensa_italia_app/android/key.jks"
      - name: Building App Bundle
        env:
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          ALIAS_PASSWORD: ${{ secrets.ALIAS_PASSWORD }}
        run: flutter pub get && flutter build appbundle --release
      - name: Make Artifact
        uses: actions/upload-artifact@v1
        with:
          name: release-apk
          path: build/app/outputs/bundle/release/app.aab
      - name: Release App Bundle
        uses: yakuhzi/action-release@v1.2.0
        with:
          file: build/app/outputs/bundle/release/app.aab