on: push
jobs:
  android_aab:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - name: android
        env:
          KEY_JKS: ${{ secrets.KEY_JKS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          ALIAS_PASSWORD: ${{ secrets.ALIAS_PASSWORD }}
        run: echo $KEY_JKS > /home/runner/work/mensa_italia_app/mensa_italia_app/android/key.jks && flutter pub get && flutter build appbundle --release
      - uses: actions/upload-artifact@v1
        with:
          name: release-apk
          path: build/app/outputs/apk/release/app-release.apk
  android_apk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - name: android
        env:
          KEY_JKS: ${{ secrets.KEY_JKS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          ALIAS_PASSWORD: ${{ secrets.ALIAS_PASSWORD }}
        run: echo $KEY_JKS > /home/runner/work/mensa_italia_app/mensa_italia_app/android/key.jks && flutter pub get && flutter build apk --release
      - uses: actions/upload-artifact@v1
        with:
          name: release-apk
          path: build/app/outputs/apk/release/app-release.apk
  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - name: macos
        env:
          KEY_JKS: ${{ secrets.KEY_JKS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          ALIAS_PASSWORD: ${{ secrets.ALIAS_PASSWORD }}
        run: echo $KEY_JKS > /home/runner/work/mensa_italia_app/mensa_italia_app/android/key.jks && flutter pub get && flutter build ios --release
