on: push
jobs:
  android_apk:
    runs-on: ubuntu-latest
    steps:
      - name: Prepearing
        uses: actions/checkout@v1
      uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      uses: subosito/flutter-action@v1.3.1
      - name: Add signing key
        env:
          KEY_JKS: ${{ secrets.KEY_JKS }}
        run: echo "$KEY_JKS" | base64 --decode > "/home/runner/work/mensa_italia_app/mensa_italia_app/android/key.jks"
      - name: Building
        env:
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          ALIAS_PASSWORD: ${{ secrets.ALIAS_PASSWORD }}
        run: flutter pub get && flutter build apk --release
      - name: Make Artifact
        uses: actions/upload-artifact@v1
        with:
          name: release-apk
          path: build/app/outputs/apk/release/app-release.apk
      - name: Release
        uses: yakuhzi/action-release@v1.2.0
        with:
          file: build/app/outputs/apk/release/app-release.apk