


on: push


jobs:

  Android_App_Bundle:
    name: Android App Bundle
    runs-on: ubuntu-latest
    steps:
      - name: Prepering Project
        uses: actions/checkout@v1

      - name: Prepering Java
        uses: actions/setup-java@v1
        with:
          java-version: '12.x'

      - name: Prepering Flutter
        uses: subosito/flutter-action@v1.3.1

      - name: Adding signing key for Play Store
        env:
          KEY_JKS: ${{ secrets.KEY_JKS }}
        run: echo "$KEY_JKS" | base64 --decode > "/home/runner/work/mensa_italia_app/mensa_italia_app/android/key.jks"

      - name: Building App Bundle
        env:
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          ALIAS_PASSWORD: ${{ secrets.ALIAS_PASSWORD }}
        run: flutter pub get && flutter build appbundle --release

      - name: Make Artifact
        uses: actions/upload-artifact@v1
        with:
          name: release-app-bundle
          path: build/app/outputs/bundle/release/app.aab

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: release
          release_name: Android App Bundle [${{ github.ref }}]
          body: |
            Changes in this Release
            - New Login Screen
          draft: false
          prerelease: false

      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: build/app/outputs/bundle/release/app.aab
          asset_name: app-release.aab
          asset_content_type: application/aab

#      - name: Upload Release To Play Store
#      - uses: r0adkll/upload-google-play@v1
#        with:
#          serviceAccountJson: ${{ SERVICE_ACCOUNT_JSON }}
#          packageName: it.mensa.app
#          releaseFile: build/app/outputs/bundle/release/app.aab
#          track: beta
#          whatsNewDirectory: /home/runner/work/mensa_italia_app/mensa_italia_app/whatsnew