

on: push


jobs:

  ####################################################################################################

  #  BUILD IOS

  ####################################################################################################

  Android_App_IOS:
    name: Android App IOS
    runs-on: macos-latest
    steps:
      - name: Prepering Project
        uses: actions/checkout@v1

      - name: Prepering Java
        uses: actions/setup-java@v1
        with:
          java-version: '12.x'

      - name: Prepering Flutter
        uses: subosito/flutter-action@v1.3.1

      - name: Building App IOS
        env:
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          ALIAS_PASSWORD: ${{ secrets.ALIAS_PASSWORD }}
        run: flutter pub get && flutter build ios --no-codesign --release

      - uses: yukiarrr/ios-build-action@v0.5.0
        with:
          project-path: ios/Runner.xcodeproj
          p12-base64: ${{ secrets.P12_BASE64 }}
          mobileprovision-base64: ${{ secrets.MOBILEPROVISION_BASE64 }}
          code-signing-identity: "iOS Distribution"
          team-id: ${{ secrets.TEAM_ID }}
          workspace-path: ios/Runner.xcworkspace



