name: Continous Integration

on:
  pull_request:
  workflow_dispatch:

jobs:
    dependabot:
      name: 'Dependabot'
      permissions: write-all
      runs-on: ubuntu-latest
      if: ${{ github.actor == 'dependabot[bot]' && github.event_name == 'pull_request'}}
      steps:
        - name: Enable auto-merge for Dependabot PRs
          run: gh pr merge --auto --merge "$PR_URL"
          env:
            PR_URL: ${{github.event.pull_request.html_url}}
            GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          continue-on-error: true
        - name: Delete workflow runs
          uses: Mattraks/delete-workflow-runs@v2
          with:
            token: ${{ github.token }}
            repository: ${{ github.repository }}
            retain_days: 0
            keep_minimum_runs: 0