on: push
jobs:
  buildios:
    name: Build iOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - run: git clone https://github.com/flutter/flutter.git --depth 1 -b v1.12.13+hotfix.9 _flutter
      - run: echo "::add-path::$GITHUB_WORKSPACE/_flutter/bin"
      - run: flutter pub get
        working-directory: ./client/flutter
      - run: flutter build ios --no-codesign
        working-directory: ./client/flutter
      - run: git diff --exit-code
  buildandroid:
    name: Build Android
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - run: git clone https://github.com/flutter/flutter.git --depth 1 -b v1.12.13+hotfix.9 _flutter
      - run: echo "::add-path::$GITHUB_WORKSPACE/_flutter/bin"
      - run: flutter pub get
        working-directory: ./client/flutter
      - run: flutter build appbundle
        working-directory: ./client/flutter
      - run: git diff --exit-code
