on: push
jobs:
  build:
    # This job will run on ubuntu virtual machine
    runs-on: ubuntu-latest
    steps:
      - name: setup-flutter
        uses: takuyaohashi/setup-flutter@v1
        env:
          KEY_JKS: ${{ secrets.KEY_JKS }}
          KEY_PASSWORD: ${{ secrets.ALIAS_PASSWORD }}
          ALIAS_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          run: echo $KEY_JKS > key.jks && flutter pub get && flutter test && flutter build apk --release


