name: Version Increase

on:
  push:
    branches:
      - master

jobs:
  clean_older_workflows:
    name: Clean older workflows
    if: "contains(github.event.commits[0].message, '[RELEASE]')"
    runs-on: ubuntu-latest
    steps:
      - name: Delete workflow runs
        uses: dmvict/clean-workflow-runs@v1.0.0
        with:
          save_period: "00:00:01"
          save_min_runs_number: 1
          token: ${{ secrets.GITHUB_TOKEN }}

  increase_version:
    name: Increase version
    needs: clean_older_workflows
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3
        
      - name: Retrieve version name
        run: |
          echo "VERSION=$(grep -oP '(?<=version: )(\d+\.\d+\.\d+)' ./pubspec.yaml)" >> $GITHUB_ENV


      - name: Increase version
        run: |
          perl -i -pe 's/^(version:\s+\d+\.\d+\.)(\d+)(\+)(\d+)$/$1.($2+1).$3.($4+1)/e' ./pubspec.yaml
    
      - name: Retrieve new version name
        run: |
          echo "NEW_VERSION=$(grep -oP '(?<=version: )(\d+\.\d+\.\d+)' ./pubspec.yaml)" >> $GITHUB_ENV

      - name: Replace all version occurrences with new version in README
        run: |
          sed -i "s/${{ env.VERSION }}/${{ env.NEW_VERSION }}/g" README.md
          
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Increase app version to ${{ env.NEW_VERSION }}
          commit_user_name: Increase Version[BOT]
          commit_user_email: matteo@sipio.it
          commit_author: Matteo Sipione <matteo@sipio.it>
          push_options: "--force"
          skip_dirty_check: true
          skip_checkout: true
          disable_globbing: true
          tagging_message: 'v${{ env.NEW_VERSION }}'


